/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hu_andun7z_AndUn7z */

#include "JniWrapper.h"

// processing callback to handler class
typedef struct tick_context {
    JavaVM  *javaVM;
    jclass   mainActivityClz;
    jobject  mainActivityObj;
} TickContext;
TickContext g_ctx;

// 압축 풀기 진행사항 함수
int progress7z(int count, int total);


JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {

    LOGI("JNI_OnLoad");

    JNIEnv* env;
    memset(&g_ctx, 0, sizeof(g_ctx));

    g_ctx.javaVM = vm;
    if ((*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6) != JNI_OK) {
        return JNI_ERR; // JNI version not supported.
    }

    g_ctx.mainActivityObj = NULL;
    return  JNI_VERSION_1_6;
}

JNIEXPORT jint JNICALL Java_com_hu_andun7z_AndUn7z_un7zip
        (JNIEnv *env, jobject instance, jstring filePath, jstring outPath) {

    // init
    jclass clz = (*env)->GetObjectClass(env, instance);
    g_ctx.mainActivityClz = (*env)->NewGlobalRef(env, clz);
    g_ctx.mainActivityObj = (*env)->NewGlobalRef(env, instance);

    // progress callback
    pFunc progressCb = progress7z;

    // processing
    jint ret = un7Zip(env, instance, filePath, outPath, progressCb);

    // release
    (*env)->DeleteGlobalRef(env, g_ctx.mainActivityClz);
    (*env)->DeleteGlobalRef(env, g_ctx.mainActivityObj);
    g_ctx.mainActivityObj = NULL;
    g_ctx.mainActivityClz = NULL;

    return ret;
}

JNIEXPORT jint JNICALL Java_com_hu_andun7z_AndUn7z_getFileCount
        (JNIEnv *env, jobject instance, jstring filePath) {

    const char *cfilePath = (*env)->GetStringUTFChars(env, filePath, 0);

    LOGD("start extract filePath[%s]", cfilePath);

    int onlyGetEntryCount = 1;
    jint ret = extract7z(cfilePath, NULL, NULL, onlyGetEntryCount);
    LOGD("end extract");

    (*env)->ReleaseStringUTFChars(env, filePath, cfilePath);

    return ret;
}

int un7Zip(JNIEnv *env, jobject instance, jstring filePath, jstring outPath, pFunc callback) {

    const char *cfilePath = (*env)->GetStringUTFChars(env, filePath, 0);
    const char *coutPath = (*env)->GetStringUTFChars(env, outPath, 0);

    LOGD("start extract filePath[%s], outPath[%s]", cfilePath, coutPath);

    jint ret = extract7z(cfilePath, coutPath, callback, 0);
    LOGD("end extract");

    (*env)->ReleaseStringUTFChars(env, filePath, cfilePath);
    (*env)->ReleaseStringUTFChars(env, outPath, coutPath);

    return 1;
}

int progress7z(int count, int total) {

    JavaVM *javaVM = g_ctx.javaVM;
    JNIEnv *env;
    jint res = (*javaVM)->GetEnv(javaVM, (void**)&env, JNI_VERSION_1_6);
    if (res != JNI_OK) {
        res = (*javaVM)->AttachCurrentThread(javaVM, &env, NULL);
        if (JNI_OK != res) {
            LOGE("Failed to AttachCurrentThread, ErrorCode = %d", res);
            return NULL;
        }
    }

    jmethodID cb = (*env)->GetMethodID(env, g_ctx.mainActivityClz, "progressCallback", "(II)V");
    if (cb == NULL) {
        LOGD("cb is NULL");
        return -1;
    }
    (*env)->CallVoidMethod(env, g_ctx.mainActivityObj, cb, count, total);

    return 1;
}

//#ifdef __cplusplus
//}
//#endif
